#! /bin/sh

# This is a script to compile markdown files into beamer pdfs through pandoc

__ScriptVersion="0.1"

#===  FUNCTION  ================================================================
#         NAME:  usage
#  DESCRIPTION:  Display usage information.
#===============================================================================
function usage ()
{
	echo "Usage :  ${0##*/} INPUTFILE [OUTPUTFILE]\n"
	echo "If OUTPUTFILE not specified, program will"
	echo "automatically remove suffix and replace  "
        echo "it with .pdf to create OUTPUTFILE.\n"


}    # ----------  end of function usage  ----------



if [[ -n $2 ]]; then
	pandoc $1 -t beamer -o $2
elif [[ -n $1 ]]; then
#https://stackoverflow.com/questions/12152626/how-can-i-remove-the-extension-of-a-filename-in-a-shell-script
	pdf=${1%.*}.pdf
	pandoc $1 -t beamer -o $pdf
else
	usage
fi


